spring:
  profiles:
    active: local

server:
  port: 8083
  servlet:
    context-path: /fabrik/api

fabrik:
  api-key: "FXOVVXXHVCPVPBZXIJOBGUGSKHDNFRRQJP"
  auth-schema: "S2S"
  time-zone: "Europe/Rome"

endpoint:
  prefix: /api/gbs/banking/v4.0/

cors:
  allowed-origins: http://localhost:8083

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html