spring:
  application:
    name: fabrik-api-v1
  profiles:
    active: local
  main:
    web-application-type: none

server:
  servlet:
    context-path: /api/fabrik/v1

springdoc:
  show-actuator: true
  use-management-port: true
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui-custom.html
  api-docs:
    path: /api-docs


endpoint:
  prefix: /api/gbs/banking/v4.0/